### PR TITLE
sbt 0.13.0

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by adrien-aubel** [comment]
Looks good to me.

**Comment by giabao** [comment]
Looks good to me.

**Comment by laughedelic** [comment]
:+1:

**Comment by havocp** [comment]
Thanks! sorry to be slow in merging.

**Comment by havocp** [comment]
trying to publish a 0.13.0 build but scripted-plugin repo is on the flake. Will figure it out

**Pull request merged**
