### PR TITLE
Trying to move toward more generality.

### PR DESCRIPTION
**Pull request by paulp**
That's where I want to get so I can use this to generate from different
templates. First I had to bring some baseline hygiene to the code. I
don't know how to preserve backward compatibility across versions of
sbt, I have a hard enough time making one version work, so I could
use some help with that part.  This is all written against 0.12.0-RC2.

### CODE REVIEW

**Comment by havocp** [comment]
This looks like a net positive (thank you) but it is really hard to review (or merge with or bisect) - it's a bunch of not-really-related changes in one big commit.

I'd like to at least separate out formatting/reindentation stuff from any substantive changes, and then see what's left. Maybe the substantive changes would be possible to subdivide as well but for the moment it's hard to pick out what the substantive changes are.

If you don't have time to do it, if your code formatting is mechanically reproducible and you tell me what formatter and settings you used, I can try to break up the patch for you. I could apply just the formatting, commit, and then diff vs. your branch to see the other stuff.

If you formatted manually then unpacking this will be more interesting.

As far as back compat across sbt versions, I think there's no answer other than testing on all of them and avoiding any changed APIs - at least, that's all I know to do. There's already at least one hack in there where I pasted in some code from a later sbt so it'd be available on earlier sbt.

**Comment by paulp** [comment]
The formatting is just what happens when I'm moving code around to remove the duplication - it's manual.  I was afraid of this; I know people don't like big patches, but it only takes a tiny bit more overhead before it's faster for me to do it from scratch.  It already is, actually, but I'm in one of those phases where I imagine it's possible for me to share code.  I was hoping the absence of any (visible) tests would imply the barrier to entry was low.

I acknowledge this is my failure, but I can't put any more time into this yak which is one of four between me and the yak I am actually after.  If something useful can be derived from it, great, if not so be it and I'll continue with my fork.

**Comment by havocp** [comment]
I picked a couple trivial things I noticed from here anyway and added scalariform so formatting should be regular (and stay that way). There are some more ideas worth picking out at some point.

**Comment by paulp** [comment]
Is that as good as scalariform can make it look? Automatic formatting sounds like a wonderful thing, but only if it does something.  I find it impossible to read without being distracted by the formatting - the heavily repeated 30+ character identifiers and the absence of any alignment beyond the left margin.

**Pull request closed without merging**
