### PR TITLE
Implements pull request #17

### PR DESCRIPTION
**Pull request by mslinn**
https://github.com/typesafehub/xsbt-start-script-plugin/issues/17

### CODE REVIEW

**Comment by havocp** [comment]
Thanks!

**Comment by havocp** [comment]
I just saw there were more commits after my comments - somehow I seem to miss a lot of github's emails :-/

It looks like you used your master branch for the pull, so there's now a lot of unrelated stuff in here including reformatting all the files. I had another request for this feature yesterday though (and in pointing them here, noticed the new commits).

**Comment by havocp** [comment]
I think what needs doing is to make a new branch off the latest master with only the relevant change (should be a fairly small patch), and a new pull request. I will plan to do it myself at some point if nobody else has time.

**Comment by mslinn** [comment]
It has been a while, I'm on to other things with deadlines so I currently don't have time to mess with this. I am not sure my patch is all it might be. You might want to look at the output for Mac/Linux, Windows and Cygwin.

**Comment by havocp** [comment]
@kriomant updated a patch for this which is now in 0.7.0

**Pull request closed without merging**
